version: "3"
services:
  frontend:
    container_name: mern_web
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_PORT: ${REACT_PORT}
    image: sylee/mern_web
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_PORT=${REACT_PORT}
    # networks:
    #   - mern-network
    env_file:
      - .env

  backend:
    container_name: mern_server
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_PORT: ${NODE_PORT}
    image: sylee/mern_server
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_PATH=src
      - NODE_ENV=production
      # - NODE_PORT=5000
    env_file:
      - .env
    # networks:
    #   - mern-network

  backend_second:
    container_name: mern_server_second
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_PORT: ${NODE_PORT_SECOND}
    image: sylee/mern_server_second
    ports:
      - "${NODE_PORT_SECOND}:${NODE_PORT_SECOND}"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_PATH=src
      - NODE_ENV=production
      - NODE_PORT=${NODE_PORT_SECOND}
    env_file:
      - .env
    # networks:
    #   - mern-network

  nginx:
    container_name: mern_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: sylee/mern_nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/mern.conf
    # networks:
    #   - mern-network
    depends_on: # nginx가 host(frontend, backend)를 인식할 수 있기 위함
      - frontend
      - backend
      - backend_second
    environment:
      - NODE_PORT=${NODE_PORT}
      - NODE_PORT_SECOND=${NODE_PORT_SECOND}
      - REACT_PORT=${REACT_PORT}
      - NGINX_PORT=${NGINX_PORT}

  mongodb:
    container_name: mern_mongo
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo:/data/db # volume을 만들어두지 않으면 컨테이너가 매번 종료될 때마다 데이터가 초기화됨
# networks:
#   mern-network:
#     driver: bridge

volumes: # mongodb 데이터
  mongo:
