version: "3"
services:
  frontend:
    container_name: mern_web
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        REACT_PORT: 3000
    image: sylee/mern_web
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_PORT=3000
    env_file:
      - .env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        NODE_PORT: 5000
    image: sylee/mern_server
    expose:
      - "5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_PATH=src
      - NODE_ENV=production
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
    env_file:
      - .env
  nginx:
    container_name: mern_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: sylee/mern_nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/mern.dev.conf
      - ./client/dist:/var/www
    depends_on:
      - frontend
      - backend
    environment:
      - NODE_PORT=5000
      - REACT_PORT=3000
      - NGINX_PORT=${NGINX_PORT}
  mongodb:
    container_name: mern_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
