version: "3"
services:
  frontend:
    container_name: mern_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sylee/mern_web
    ports:
     - "3000:3000"
    volumes:
     - ./client:/usr/src/app
     - /usr/src/app/node_modules
  backend:
    container_name: mern_server
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: sylee/mern_server
    ports: 
     - "5000:5000"
    volumes:
     - ./server:/usr/src/app
     - /usr/src/app/node_modules
