name: CI/CD PROD

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          timeout: 30m
          command_timeout: 60m
          script: |
            mkdir -p /home/cookbook/prod
            cd /home/cookbook/prod
            git remote add origin https://github.com/${{github.repository}}
            git clone https://github.com/${{github.repository}} .
            git checkout ${{github.head_ref}}
            git pull origin ${{github.head_ref}}
            echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" >> "./.env"
            echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> "./.env"
            echo "CLOUDINARY_SECRET=${{secrets.CLOUDINARY_SECRET}}" >> "./.env"
            echo "NODE_PORT=${{secrets.NODE_PORT}}" >> "./.env"
            echo "REACT_PORT=3000" >> "./.env"
            echo "NGINX_PORT=90" >> "./.env"
            cat ./.env
            docker-compose -f "docker-compose.yml" up -d --build
